#!/bin/sh

# cont

err="err"
out="out"
remotescript="/tmp/script"

# end of conf

if [ $# -ne 2 ]; then
	echo "Usage: $0 script hosts"
	exit
fi

script="$1"
hosts="$2"

args="-o $out -e $err -h $hosts"

parallel-scp $args "$script" "$remotescript"

exec < "$hosts"

tmp=0
while read remote
do
	f="$err/$remote"
	if [ -s "$f" ]; then
		echo "Errors: $f"
		tmp=1
	fi
done
if [ "$tmp" = 1 ]; then
	echo "Errors: Exiting"
	exit
fi

parallel-ssh $args "chmod 755 \"$remotescript\" ; \"$remotescript\" ; echo \"Exit code: \$?\" ; rm -f \"$remotescript\""

exec < "$hosts"

tmp=0
while read remote
do
	f="$err/$remote"
	if [ -s "$f" ]; then
		echo "Errors: $f"
		tmp=1
	fi
	f="$out/$remote"
	if [ -s "$f" ]; then
		echo "Output: $f"
	fi
done
if [ "$tmp" = 1 ]; then
	echo "Errors: Exiting"
	exit
fi

